### ISSUE TITLE
Incorrect changeset for tags

### ISSUE THREAD

**Issue by pedrocarrico** [gaffneyc/heroku-buildpack-jemalloc#21]
Hi!

I was installing the buildpack and pinning it over to our stack version of `heroku-20` and used the same tag on this repo but noticed that all the tags point to the same commit SHA.

<img width="506" alt="Screenshot 2021-02-03 at 16 11 23" src="https://user-images.githubusercontent.com/151290/106909605-5cd02700-66f8-11eb-958d-85bf5d0f56c0.png">

Should I just pin it to the commit SHA instead?Or are the tags intended to point to the actual commit?

Thanks!

**Comment by gaffneyc** [comment]
@pedrocarrico

Oh! I totally see the confusion there. You should use master instead of pinning to a release.

The way the buildpack works is that it's essentially a set of scripts to download precompiled binaries for each stack. We use GitHub's releases as an easy way to host those binaries but the releases themselves point to a detached commit. Fortunately this means that when you update your stack the next deploy will automatically fetch the correct binaries. It also means that it's easy for us to support a new stack.

To answer your question: you should just pin to master. The tags are there because we have to have a tag to have a release and the releases are used to serve the binaries.

**Comment by pedrocarrico** [comment]
@gaffneyc Thanks for clearing that up!
Makes sense now with explanation 👍
