### ISSUE TITLE
Support for heroku-24 stack

### ISSUE THREAD

**Issue by prognostikos** [gaffneyc/heroku-buildpack-jemalloc#38]
Good morning.

I will make a PR for support for the heroku-24 stack, would you also like me to remove support for heroku-18 at the same time or would you prefer two separate PRs?

**Comment by gaffneyc** [comment]
See #35

Since changing to jemalloc being built during the compile phase we don’t need do anything to support new stacks when they’re released. We’ve been running on heroku-24 for a while so everything is working as it should.

The only case we would need to build binaries is if someone pinned a deploy to a specific commit. In that case I’d recommend updating to the latest version as the new way removes one potential source of a supply chain attack (i.e. me building malicious code into the binaries that are deployed)

**Comment by prognostikos** [comment]
Thanks for the update. Not sure why I thought it wasn't building on heroku-24 but I just tested and it works fine. Sorry for the noise.
