### ISSUE TITLE
heroku-24

### ISSUE THREAD

**Issue by johnnagro** [gaffneyc/heroku-buildpack-jemalloc#39]
could we have some heroku-24 stack builds please & thank you

**Comment by gaffneyc** [comment]
Please see #35

Since [changing to jemalloc being built during the compile phase](https://github.com/gaffneyc/heroku-buildpack-jemalloc/commit/d66c61a7384a34fc376a799e2522ec247d8913a1) we don’t need to do anything to support new stacks when they’re released. We’ve been running on heroku-24 for a while so everything is working as it should.

The only case we would need to build binaries is if someone pinned a deploy to a specific commit. In that case I’d recommend updating to the latest version as the new way removes one potential source of a supply chain attack (i.e. me building malicious code into the binaries that are deployed). Feel free to reopen the issue if that's not an option.
